spring:
  datasource:
    url: jdbc:h2:mem:spring_jpa_test_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect